server:
  port: 5103

spring:
  application:
    name: service-provider 
  datasource:
    name: mydb
    url: jdbc:mysql://localhost:3306/shopdb
    username: root 
    password: root 
    driver-class-name: com.mysql.cj.jdbc.Driver 

mybatis:
  mapper-locations: classpath:mapper/*.xml 
  type-aliases-package: com.example.provider.domain 
  config-location: classpath:mybatis/mybatis-config.xml

eureka:
  instance:
    prefer-ip-address: true      
    instance-id: ${spring.cloud.client.ip-address}:${server.port} 
  client:
    service-url:               
      defaultZone: http://admin:123456@localhost:7000/eureka/


management:
  endpoints:
    web:
      exposure:
        include: shutdown       
  endpoint:
    shutdown:
      enabled: true             
